namespace OpenPlanTrace;

public sealed record PipelineArtifactPlan(
    PlanArtifactKind Artifact,
    bool IsSourceArtifact,
    bool IsProducedByStage,
    bool IsConsumedByStage,
    bool IsTerminalArtifact,
    IReadOnlyList<string> ProducerStages,
    IReadOnlyList<string> RequiredConsumerStages,
    IReadOnlyList<string> OptionalConsumerStages,
    IReadOnlyList<string> ConsumerStages,
    int ProducerCount,
    int ConsumerCount,
    int FirstProducerOrder,
    int LastProducerOrder,
    int FirstConsumerOrder,
    int LastConsumerOrder,
    int FirstProducerWave,
    int LastProducerWave,
    int FirstConsumerWave,
    int LastConsumerWave,
    bool HasMultipleProducers,
    bool HasRequiredConsumers,
    string DependencyRole,
    IReadOnlyList<string> Evidence);
